### ISSUE TITLE
Chat Background

### ISSUE THREAD

**Issue by KyokiVHS** [giambaJ/jChat#1]
Would be very helpful if you could add an option to change to background from transparent to a solid color like black or whatever the user might wish the background color of the chat to be. Could help with readability of the on screen chat since when its transparent in certain streams scenes its difficult to read.

**Comment by giambaJ** [comment]
I could add some background customization in the future, but in the meantime there are multiple ways you can achieve that on your own. The easy way is adding `body {background-color: <color> !important;}` in the CSS field of your browser source, with **\<color\>** being a color name from [**this list**](https://www.w3schools.com/cssref/css_colors.asp) or an HEX/RGB/HSL value.
