### ISSUE TITLE
Width and Height

### ISSUE THREAD

**Issue by 3bood-k** [giambaJ/jChat#14]
Thank you for jChat ,, your tool helped a lot ❤️

It's really awesome but there's an important feature missing. We hope you add "**Width and Height**" control before generating the link for OBS browser source.

![](https://cdn.discordapp.com/attachments/831493135132786718/906659328977682473/jChat_idea.jpg)

**Comment by giambaJ** [comment]
I'm not sure what you mean. You can choose whatever width and height when you set up your browser source, just like you did in your screenshots.

**Comment by 3bood-k** [comment]
My idea is that you can set the chat width so that the person's writing is not shown in one long line, but rather more than one line.

![](https://cdn.discordapp.com/attachments/834029998272413756/921528282959183932/unknown.png)

**Comment by giambaJ** [comment]
You can set the chat width when you create your browser source. jChat will adapt to whatever size you choose for your source, not the other way around.
![Immagine 2021-12-18 005431](https://user-images.githubusercontent.com/68540706/146620538-23344d52-bc69-4ec7-a836-019468d510c9.png)

**Comment by 3bood-k** [comment]
Thank you very much, it didn't cross my mind, and I'm sorry I didn't understand that very well.
keep developing jChat because it helped me a lot and helped streamers ❤️
