### ISSUE TITLE
[ Feature ] - Chat delay - end of life twitch v5

### ISSUE THREAD

**Issue by Dschogo** [giambaJ/jChat#17]
Hey awesome project.

To give mods the possibility to mod timewise it would be nice to have an option for delay (1-5 seconds should be plenty). 
Currently a friend of mine just uses the "render delay" inside Streamlabs on the chat source, but that also obviously applies to deleted messages. (Like new messages take x seconds to appear, but also x seconds to get removed after deletion).

Think that would be a neat and pretty easy to implement feature

Additionally i've seen ur using a credential.js for the client id. twitch irc can be connected to without that as you do with Nick justinfan. Can't the cheers stuff be loaded without creds too? (works also without login on normal twitch page)
This should be necessary due to end of life of twitch api v5 on 22.02

**Comment by giambaJ** [comment]
Hey there. The delay option will be added in the v3 update with a bunch of other features. This update has taken more time than I wanted to but should come fairly soon.
As for the client id, that is required for the cheermotes API. Not sure why I'm still using the v5 endpoint but thanks for reminding me.
