### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by Konki29** [giambaJ/jChat#20]
Is there any form to custom the style of the css ? I tried and it doesn't save on the file system so i guess it request out on the github, I don't have so much idea of that so I would like to know if there is any form to do that.

**Comment by giambaJ** [comment]
I'm not sure what you mean. You can add custom CSS in OBS when you add the browser source.

**Comment by arrowgent** [comment]
yep, you can add custom css through obs source or edit the index.html and point to a css file to override

if youre familiar with html/css coding it should not be an issue for you to do this


`    <link rel="stylesheet" href="./custom/mychat.css">`
