### ISSUE TITLE
Kraken deprecation has made jChat unusable.

### ISSUE THREAD

**Issue by treejadey** [giambaJ/jChat#21]
Due to the Twitch Kraken API deprecation, jChat has stopped working.

Could you please make a temporary fix to make it work on Helix instead of Kraken. Or, at least, provide an update as to when the third version comes out. Thank you.

**Comment by giambaJ** [comment]
Twitch API v5 is scheduled to stop working on February 28, 2022. I've been super busy, but the update will be released in the next couple of weeks.
If you're having technical issues, you can contact me on Discord (giambaJ#9167) and we'll work it out.
