### ISSUE TITLE
[api] twitch kraken v5 deprecation

### ISSUE THREAD

**Issue by arrowgent** [giambaJ/jChat#24]
https://github.com/giambaJ/jChat/blob/86a0b95fcf303ed684d3367dad2b218181ab209b/v2/script.js#L96

`TwitchAPI('https://api.twitch.tv/v5/users?login=`
{"error":"Not Found","status":404,"message":"This API does not exist"}

still using v5 login credentials
need to merge to helix authentication

`https://api.twitch.tv/helix/users?login=`
or similar.  unsure how to move to this within your scripting.

`{"error":"Unauthorized","status":401,"message":"OAuth token is missing"}`
need to add oauth token to the helix connection

```
v5 shutdown timeline
Given the number of v5 migrations, we wanted to ensure that you have sufficient time to update your applications and that we are reaching developers as soon as possible. A phased shutdown of v5 will begin in February 2022. Here are the shutdown windows:

February 7, 2022 – 1-hour shutdown starting at 11:00am PDT
February 9, 2022 – 2-hour shutdown starting at 11:00am PDT
February 14, 2022 – 4-hour shutdown starting at 11:00am PDT
February 16, 2022 – 6-hour shutdown starting at 11:00am PDT
February 21, 2022 – 24-hour shutdown starting at 11:00am PDT
February 28, 2022 – v5 permanent shutdown
```

https://dev.twitch.tv/docs/api/reference
some helix reference

**Comment by arrowgent** [comment]
sorry, should have looked at closed first

https://github.com/giambaJ/jChat/issues/21

**Comment by arrowgent** [comment]
actually,

providing a basic credentials.js with blank info would be useful
indicate the oauth & client id fields for people to create their own

https://github.com/giambaJ/jChat/blob/86a0b95fcf303ed684d3367dad2b218181ab209b/v2/index.html#L18

**Comment by arrowgent** [comment]
based on what you have modified but not updated here on github

old
```
/*function TwitchAPI(url) {
    return $.getJSON(url + (url.search(/\?/) > -1 ? '&' : '?') + 'client_id=' + client_id);
}*/
```

new
```
function myAPI(url) {
    return $.ajax({
        beforeSend: function(request) {
            request.setRequestHeader("Authorization", "Basic " + btoa(credentials));
        },
        dataType: "json",
        url: "https://api.giambaj.it" + url
    });
}
```
your modification provides the helix RequestHeader
but youre using ajax on your server to handle the auth
preferable to directly query `https://api.twitch.tv/helix/users?login=`

using your credentials.js (example)

```
const client_id = 'clientid_token?';
const credentials = 'oauth?token';
// userid#
```

and i think missing (or running server side) 
```
curl -s -X GET "https://api.twitch.tv/helix/users?login=$channel" \
                -H "Authorization: Bearer $oauth" \
                -H "Client-Id: $clientid")
```

**Comment by arrowgent** [comment]
ah....

i see now, youre not really logging in, youre using the kraken api to get userid# in the json
so lets me see how to do the same in helix api

been trying to rewrite this to access helix

**Comment by arrowgent** [comment]
authenticate
```
function TwitchAPI(url) {
    return $.ajax({
        type: "GET", 
        url: "https://id.twitch.tv/oauth2/validate", 
        dataType: "json",
        headers: {'Authorization': 'Bearer ' + credentials},
/*        headers: {'Client-Id': client_id},*/
        success : function(result) { 
            console.log('jChat: helix json aquired user_id');
        }
    });
}
```

get json userid
```
    load: function(callback) {
        TwitchAPI('https://api.twitch.tv/helix/users?login=' + Chat.info.channel).done(function(res) {
/*            res = res['Message'];*/
            Chat.info.channelID = res.user_id;
/*            Chat.info.channelID = res.users[0]._id;*/
            Chat.loadEmotes(Chat.info.channelID);
```
^ this is not really required `TwitchAPI` the json user_id is already stored as a variable

```
    load: function(callback) {
        TwitchAPI().done(function(res) {
            Chat.info.channelID = res.user_id;
```
removed unused url call

credentials.js (your credentials -- secret_token is required)
```
const client_id = 'clientid_token?';
const credentials = 'oauth?token';
// userid#
```


an output example of helix users?login

```
{
  "data": [
    {
      "id": "691199840",
      "login": "justinfan",
      "display_name": "justinfan",
      "type": "",
      "broadcaster_type": "",
      "description": "",
      "profile_image_url": "https://static-cdn.jtvnw.net/user-default-pictures-uv/cdd517fe-def4-11e9-948e-784f43822e80-profile_image-300x300.png",
      "offline_image_url": "",
      "view_count": 87,
      "created_at": "2021-05-26T22:58:45Z"
    }
  ]
}
```

a problem with helix oauth tokens is they are only good for 60 days.
im just reusing a bot's token that gets refreshed often.

**Comment by giambaJ** [comment]
Yeah, the thing is jChat was always meant to be a fully client-side application for a number of reasons. I'm using my API to handle helix requests so I don't have to manually refresh the bearer token every time it expires (my API server does it autonomously). This is just temporary.
Thanks for your research anyway.

**Comment by arrowgent** [comment]
indeed, im running it clientside locally in my obs folder

the authenticate: bearer & client_id are the only hurdles here for getting userid

**Comment by arrowgent** [comment]
with client_id and bearer auth we get from helix

```
curl -s -X GET "https://api.twitch.tv/helix/users?login=USERNAME" \
-H "Authorization: Bearer OAUTH" \
-H "Client-Id: CLIENT_TOKEN"
```


```
{
  "data": [
    {
      "id": "258486933",
      "login": "giambaj",
      "display_name": "giambaJ",
      "type": "",
      "broadcaster_type": "",
      "description": "bella lì",
      "profile_image_url": "https://",
      "offline_image_url": "https://",
      "view_count": 306,
      "created_at": "2018-09-14T17:22:25Z"
    }
  ]
}
```

so this would require
`            Chat.info.channelID = res.id;`


-

if we only use the bearer oauth using validation
https://id.twitch.tv/oauth2/validate

```
curl -s -X GET "https://id.twitch.tv/oauth2/validate" \
                -H "Authorization: Bearer OAUTH"
```

```
{"client_id":"OAUTH",
"login":"USERNAME",
"scopes":["chat_login",
"user_blocks_edit",
"user_blocks_read",
"user_follows_edit",
"user_read",
"user_subscriptions"],
"user_id":"USERID#",
"expires_in":0}
```

which requires
`            Chat.info.channelID = res.user_id;`

**Comment by arrowgent** [comment]
since the author only updates his webpage and doesnt have any published updates here to fix the issue
or look at the PullRequest to give a solution

**ive also told him that his oauth key and clientid are publically visible on his website.  anyone can view them and reuse them effectively giving full control as that user.**
https://github.com/giambaJ/jChat/pull/27#issuecomment-1057426651
https://github.com/KevinKYeh/kChatV2/commit/f4ec1914f858befd9a2687ff928d7817ff282a60

**_i'll shortly end up closing this, my PR, and deleting my contribution_**
i dont intend to maintain a fork of this that adds features and improves the issues

anyone wishing to use jChat locally stored on their own computer and edit the files to fit their modified designs can look at the previous PR for a solution
https://github.com/KevinKYeh/kChatV2


https://github.com/giambaJ/jChat/issues/17
