### ISSUE TITLE
Zero-width/hat emotes support

### ISSUE THREAD

**Issue by sunkhaskasis** [giambaJ/jChat#3]
I'm sure this is a known issue, but is there a chance we could get a proper support for this type of emotes? I'm not a coder myself and I don't know how complicated it'd be, so you are free to close the issue if it's currently out of scope.

**Comment by giambaJ** [comment]
I'll add zero-width support in the next update.

**Comment by giambaJ** [comment]
Zero-width emotes are now supported with [v2.3.4](https://github.com/giambaJ/jChat/commit/345d92edf7d83149505078a8c02352205181d43d).

**Comment by sunkhaskasis** [comment]
Sorry if I'm too early and you haven't pushed the changes yet, but zero-width emotes still don't work on my end.
![image](https://user-images.githubusercontent.com/19194315/131216563-707c9ca5-a67c-468a-8a9b-f67c6f592c64.png)

**Comment by giambaJ** [comment]
> Sorry if I'm reporting too early and you haven't pushed the changes yet, but zero-width emotes still don't work on my end.
> ![image](https://user-images.githubusercontent.com/19194315/131216563-707c9ca5-a67c-468a-8a9b-f67c6f592c64.png)

Try CTRL+F5 refreshing.

**Comment by sunkhaskasis** [comment]
Thanks, all good now.
![image](https://user-images.githubusercontent.com/19194315/131219649-0fc4c210-5086-4bda-90df-f1662fa3ecbe.png)
