### ISSUE TITLE
Ignore user's chat option

### ISSUE THREAD

**Issue by ProjectXsent** [giambaJ/jChat#31]
I'm not sure if I can place a suggestion here but I hope there's a feature that I can ignore a person/user's chat on the chat overlay like it won't show the message on the overlay.

**Comment by piebandit** [comment]
You can ignore specific user messages by adding this CSS code to the Custom CSS section in the browser source properties in OBS.

Replace USERNAME, with the actual username of the account, all lowercase.
`div[data-nick="USERNAME"] { display: none !important; }`

**Comment by ProjectXsent** [comment]
What if I add another user, should I use the same line again but change the nickname? Or just go

div[data-nick="USERNAME1", "USERNAME2",...] { display: none !important; }

Edit: Never mind, the former works which is
div[data-nick="USERNAME1"] { display: none !important; }
div[data-nick="USERNAME2"] { display: none !important; }

and thank you for the response 💖

**Comment by piebandit** [comment]
You could add multiple by separating them using commas, or you could do multiple lines like you did.

`div[data-nick="USERNAME1"], div[data-nick="USERNAME2"] { display: none !important; }`
