### ISSUE TITLE
Just stopped working?

### ISSUE THREAD

**Issue by TheRealDadbeard** [giambaJ/jChat#33]
I just get no output on my browser source at all. Is something broken?

**Comment by go1t** [comment]
yeah it doesn't work for me as well. I checked the console and it seems like twitch returns 401 when jChat is trying to get `https://api.twitch.tv/helix/users?login=<username>` 🤔

**Comment by dazednova** [comment]
can confirm

**Comment by Vereor** [comment]
Looks like an auth issue with the twitch API
{"error":"Unauthorized","status":401,"message":"OAuth token is missing"}

**Comment by giambaJ** [comment]
Should be fixed.
