### ISSUE TITLE
No Chatterino badges

### ISSUE THREAD

**Issue by sunkhaskasis** [giambaJ/jChat#5]
I see that the description mentions Chatterino badges one can toggle on and off, but it appears that they aren't displayed at all. Here's a screenshot from Chatterino:
![yesbadge](https://user-images.githubusercontent.com/19194315/129456219-25828499-a3c7-420c-81a2-6e8dec4a167a.PNG)

And from the jChat overlay:
![nobadge](https://user-images.githubusercontent.com/19194315/129456229-cb08ec4f-cdbe-4657-8f50-56dd472e3a0b.PNG)

I did check that the special badges were enabled.

**Comment by giambaJ** [comment]
Yep that last update isn't live yet. It will in a couple of days.

**Comment by giambaJ** [comment]
Chatterino badges should now work.
